import { describe, expect, it } from 'vitest';

import { MTL_OUTPUT_NAME_COLLISION } from '../../src/contracts/index.js';
import { createOutputBuilder } from '../../src/materialize/context.js';
import { outputCollisionDiagnostics } from '../../src/materialize/serialize.js';

// T014: context.spec.ts — OutputBuilder + output collision (FR-013).
// serializeOutputs is gone (spec 016 migration T059); the merged outputs file
// is generated by buildOutputs. Materializer-level collision detection stays.

describe('context.ts / OutputBuilder + output collision (MTL_OUTPUT_NAME_COLLISION)', () => {
  it('T014: OutputBuilder first-wins declare; duplicate name recorded and reported as MTL_OUTPUT_NAME_COLLISION (FR-013, Sc13)', () => {
    const builder = createOutputBuilder();
    builder.declare('url', { value: 'function_url(user_service)', description: 'URL' });
    // Second declare from another artifact with the same name.
    builder.declare('url', { value: 'function_url(analytics)', description: 'DUP' });

    expect([...builder.declared.keys()]).toEqual(['url']);
    expect(builder.declared.get('url')?.value).toBe('function_url(user_service)');
    expect(builder.duplicateNames).toEqual(['url']);

    const diagnostics = outputCollisionDiagnostics(builder.duplicateNames);
    expect(diagnostics).toHaveLength(1);
    expect(diagnostics[0]).toMatchObject({ code: MTL_OUTPUT_NAME_COLLISION, outputName: 'url' });
  });
});